### ISSUE TITLE
Overspawning garden eels (possible mod incompatibilty) 

### ISSUE THREAD

**Issue by CletusMAngo** [TeamDraco/UnnamedAnimalMod#2]
Title explains enough ^ but whats weird is some people dont get the overspawning but others do 
![image](https://user-images.githubusercontent.com/76655777/123635803-5fa0f500-d81c-11eb-9714-33ea6ff7cc21.png)

**Comment by Coda1552** [comment]
Should be fixed in 1.0.1.
