### ISSUE TITLE
Fish models appear sideways in JER

### ISSUE THREAD

**Issue by KekLeon** [TeamDraco/UnnamedAnimalMod#4]
![2021-07-01_03 00 52](https://user-images.githubusercontent.com/68141017/124081016-04882180-da19-11eb-8718-25c644c8e0c8.png)
![2021-07-01_03 00 59](https://user-images.githubusercontent.com/68141017/124081019-04882180-da19-11eb-8e5d-055dfa5e7b5a.png)
![2021-07-01_03 01 04](https://user-images.githubusercontent.com/68141017/124081020-04882180-da19-11eb-9bb6-f21d7b0db04a.png)
![2021-07-01_03 01 20](https://user-images.githubusercontent.com/68141017/124081021-0520b800-da19-11eb-8c98-0abf5e1c1e0b.png)

**Comment by Coda1552** [comment]
It does this because the animal is rotated in code when it's on land, there's not much we can do about this, afaik. If you (or anyone else) know how, please let me know.
